services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - env_docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    container_name: database

  backend:
    build: ./backend
    restart: always
    env_file:
      - env_docker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    container_name: backend

  frontend:
    container_name: frontend
    build: ./client
    depends_on:
      - backend

    restart: always 
    environment:
      - VITE_API_URL=http://localhost:8000/api
      
    ports:
      - "80:80"
      - "443:443"

      
volumes:
  postgres_data: